module-item-order-groupings = [
  [
    "use",
    [
      "use",
    ],
  ],
  [
    "modules",
    [
      "extern_crate",
      "mod",
      "foreign_mod",
    ],
  ],
  [
    "macros",
    [
      "macro",
    ],
  ],
  [
    "global_asm",
    [
      "global_asm",
    ],
  ],
  [
    "UPPER_SNAKE_CASE",
    [
      "static",
      "const",
    ],
  ],
  [
    "PascalCase",
    [
      "ty_alias",
      "enum",
      "struct",
      "union",
      "trait",
      "trait_alias",
      "impl",
    ],
  ],
  [
    "lower_snake_case",
    [
      "fn",
    ],
  ],
]
source-item-ordering = ["module"]
